import { Navbar } from '@/components/navbar';
import './globals.css';
import { Inter } from 'next/font/google';
import { navItems } from '@/config/nav-items';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`max-w-6xl mx-auto my-0 ${inter.className}`}>
        {/* @ts-expect-error Async Server Component */}
        <Navbar items={navItems} />
        {children}
      </body>
    </html>
  );
}
